version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: coffee
      POSTGRES_PASSWORD: coffee
      POSTGRES_DB: coffee
    ports:
      - '5432:5432'
    volumes:
      - ./coffee-data:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:6.2
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  coffee-data:
